# 基本設定
agent_name: "通話データ管理エージェント"
agent_description: "通話データの分析と情報提供を行います"
host: "localhost"
port: 8008
llm_model: "gpt-4.1-nano"
data_source: "../data/calls.csv"

# A2A設定
organization: "あなたの会社名"
version: "1.0.0"
endpoint: "/a2a"

# UI/UX設定
defaultInputModes: ["text"]
defaultOutputModes: ["text"]

# スキル定義
skills:
  - id: "analyze_calls"
    name: "通話情報分析"
    description: "通話データに関する情報を自然言語で分析します。ログID,発信日時,発信者ID,発信者電話番号,着信者ID(取引先等),着信者電話番号,通話時間(秒)の情報を保持しています。"
    examples:
      - "部門別の外部通話量を分析してください"
      - "従業員Aの通話履歴を表示してください"
    inputModes: ["text"]
    outputModes: ["text"] 
