# 基本設定
agent_name: "メールデータ管理エージェント"
agent_description: "社内外メールデータの分析と情報提供を行います"
host: "localhost"
port: 8007
llm_model: "gpt-4.1-nano"
data_source: "../data/communications.csv"

# A2A設定
organization: "あなたの会社名"
version: "1.0.0"
endpoint: "/a2a"

# UI/UX設定
defaultInputModes: ["text"]
defaultOutputModes: ["text"]

# スキル定義
skills:
  - id: "analyze_communications"
    name: "メール情報分析"
    description: "メールデータに関する情報を自然言語で分析します。ログID,日時,送信者ID,送信者アドレス,受信者ID,受信者アドレス/グループ名,種別,件名,キーワードフラグ,業務外フラグの情報を保持しています。"
    examples:
      - "社外とのメール量の推移を教えてください"
      - "特定キーワードを含むメールを検出してください"
      - "業務外メールを検出してください"
    inputModes: ["text"]
    outputModes: ["text"]