# 基本設定
agent_name: "従業員データ管理エージェント"
agent_description: "従業員データの分析と情報提供を行います"
host: "localhost"
port: 8006
llm_model: "gpt-4.1-nano"
data_source: "../data/employees.csv"

# A2A設定
organization: "あなたの会社名"
version: "1.0.0"
endpoint: "/a2a"

# UI/UX設定
defaultInputModes: ["text"]
defaultOutputModes: ["text"]

# スキル定義
skills:
  - id: "analyze_employees"
    name: "従業員データ分析"
    description: |
      従業員データを自然言語で分析します。従業員ID,氏名,所属部署,役職,入社年月日,最終異動日,懲戒歴フラグの情報を保持しています。
    examples:
      - "従業員IDがXXXの情報を教えてください"
      - "部門別の平均勤続年数を分析してください"
      - "職位別の従業員分布を教えてください"
      - "最近の人事異動パターンを分析してください"
    inputModes: ["text"]
    outputModes: ["text"] 
