# 基本設定
agent_name: "経費データ管理エージェント"
agent_description: "経費データの分析と情報提供を行います"
host: "localhost"
port: 8005
llm_model: "gpt-4.1-nano"
data_source: "../data/expenses.csv"

# A2A設定
organization: "あなたの会社名"
version: "1.0.0"
endpoint: "/a2a"

# UI/UX設定
defaultInputModes: ["text"]
defaultOutputModes: ["text"]

# スキル定義
skills:
  - id: "analyze_expenses"
    name: "経費情報分析"
    description: "経費データに関する情報を自然言語で分析します。精算ID,申請日,申請者ID,申請者名,経費種別,支払先,利用日,金額,目的,参加者,関連取引先IDの情報を保持しています。"
    examples:
      - "部門別の経費使用状況を分析してください"
      - "経費カテゴリ別の使用割合を教えてください"
      - "経費の多い取引先を教えてください"
    inputModes: ["text"]
    outputModes: ["text"] 
