# 基本設定
agent_name: "支払データ管理エージェント"
agent_description: "支払データの分析と情報提供を行います"
host: "localhost"
port: 8003
llm_model: "gpt-4.1-nano"
data_source: "../data/payments.csv"

# A2A設定
organization: "あなたの会社名"
version: "1.0.0"
endpoint: "/a2a"

# UI/UX設定
defaultInputModes: ["text"]
defaultOutputModes: ["text"]

# スキル定義
skills:
  - id: "analyze_payments"
    name: "支払情報分析"
    description: "支払データに関する情報を自然言語で分析します。支払ID,支払日,取引先ID,取引先名,支払金額,支払先口座名義,関連請求書ID,支払方法の情報を保持しています。"
    examples:
      - "支払遅延が発生している取引先を教えてください"
      - "従業員Aの支払履歴を表示してください"
    inputModes: ["text"]
    outputModes: ["text"] 
