# 基本設定
agent_name: "稟議書・申請書データ管理エージェント"
agent_description: " 稟議書・申請書データの分析と情報提供を行います"
host: "localhost"
port: 8009
llm_model: "gpt-4o-mini"
data_source: "../data/requests.csv"

# A2A設定
organization: "あなたの会社名"
version: "1.0.0"
endpoint: "/a2a"

# UI/UX設定
defaultInputModes: ["text"]
defaultOutputModes: ["text"]

# スキル定義
skills:
  - id: "query_request"
    name: "稟議書・申請書情報検索"
    description: "稟議書・申請書情報を自然言語で検索します"
    examples:
      - "稟議書IDがR001の詳細情報を教えてください"
      - "先月の未処理稟議書数を教えてください"
      - "優先度の高い稟議書を一覧表示してください"
    inputModes: ["text"]
    outputModes: ["text"]
  
  - id: "analyze_requests"
    name: "稟議書・申請書傾向分析"
    description: "稟議書・申請書データの傾向分析を行います"
    examples:
      - "部門別の稟議書・申請書傾向を分析してください"
      - "稟議書・申請書処理時間の推移を教えてください"
      - "異常な処理遅延が発生しているケースを特定してください"
    inputModes: ["text"]
    outputModes: ["text"] 
